# Config file for training WaveNeXt model

duration: 1
#duration: 0.68

# Model hyperparameters
#sample_rate: 48000 
sample_rate: 48000

#fft_dim: 2048
fft_dim: 2048

dim: 512
#shift_dim: 512
shift_dim: 512
n_mels: 80
k: 3

# Training hyperparameters
batch_size: 8
num_workers: 16
num_epochs: 1000
learning_rate: 0.0002
log_dir: "logs"

accelerator: "cuda"
devices: 1

dataset: "data/bach_violin_dataset.csv"

resume: false
